# Generated by Django 5.0.1 on 2026-03-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
